[Database]
Driver = "sqlite"
Name = "matebot-web.sqlite"
Host = ""
Port = 3306
User = ""
Password = ""

[MateBot]
BaseUrl = ""
Username = ""
Password = ""
CallbackUrl = ""
CallbackSecret = ""

[MateBot.Currency]
Digits = 2
Factor = 100
Symbol = "€"

[Server]
Listen = "127.0.0.1:8000"
AllowedHosts = [
    {Host = "127.0.0.1:8000", Https = false},
]
UseForwardedProtoHeader = false
TemplateDir = "templates/"
StaticDir = "static/"